// Model: chữ hiển thị màn hình đăng nhập/đăng ký (VI/EN) + danh sách theme.
export const AUTH_THEMES = [
  { id: "glass", dot: "td-glass", name: "Modern Glassmorphism" },
  { id: "neu", dot: "td-neu", name: "Soft UI / Neumorphism" },
];

export const AUTH_TEXT = {
  vi: {
    tagline: "Quản lý chi tiêu thông minh cho sinh viên",
    login: "Đăng nhập",
    register: "Đăng ký",
    name: "Họ tên đầy đủ",
    username: "Username",
    email: "Email",
    phone: "Số điện thoại",
    password: "Mật khẩu",
    confirm: "Xác nhận mật khẩu",
    forgot: "Quên mật khẩu?",
    submitLogin: "Đăng nhập",
    submitRegister: "Tạo tài khoản",
    noAcc: "Chưa có tài khoản?",
    hasAcc: "Đã có tài khoản?",
    goRegister: "Đăng ký ngay",
    goLogin: "Đăng nhập",
    streakLogin:
      "Đăng nhập mỗi ngày để duy trì chuỗi đăng nhập — chuỗi được ghi nhận sau khi đăng nhập thành công.",
    streakRegister:
      "Sau khi đăng ký, hãy đăng nhập liên tục để duy trì chuỗi đăng nhập của bạn.",
    errFill: "Vui lòng điền đầy đủ tất cả thông tin.",
    errLogin: "Vui lòng nhập email và mật khẩu.",
    errLen: "Mật khẩu cần đủ 8 ký tự, chữ hoa, chữ thường, số và ký tự đặc biệt.",
    pwStrength: "Độ mạnh mật khẩu",
    pwWeak: "Yếu",
    pwFair: "Trung bình",
    pwGood: "Tốt",
    pwStrong: "Mạnh",
    pwEight: "8 ký tự",
    pwUpper: "A–Z",
    pwLower: "a–z",
    pwNumber: "0–9",
    pwSpecial: "@#$",
    errMatch: "Mật khẩu xác nhận không khớp.",
    errEmailOnly: "Vui lòng nhập email.",
    errInvalidCreds: "Email hoặc mật khẩu không đúng.",
    errEmailTaken: "Email này đã được đăng ký.",
    errNotConfirmed: "Tài khoản chưa xác nhận. Vui lòng kiểm tra email.",
    errTooMany: "Bạn thao tác quá nhanh, vui lòng thử lại sau ít phút.",
    errNetwork: "Không kết nối được máy chủ. Kiểm tra lại mạng.",
    errLocked: "Tài khoản đã bị khoá. Vui lòng liên hệ quản trị viên.",
    errProfile: "Không tải được hồ sơ người dùng. Vui lòng thử lại.",
    errPhone: "Số điện thoại chỉ gồm 9–15 chữ số (có thể bắt đầu bằng +).",
    errUsernameTaken: "Username này đã có người dùng.",
    registered: "Đăng ký thành công! Vui lòng đăng nhập.",
    loading: "Đang xử lý…",
    forgotTitle: "Khôi phục mật khẩu",
    forgotDesc: "Nhập email đã đăng ký để đặt lại mật khẩu.",
    emailLabel: "Địa chỉ Email",
    emailPlaceholder: "Nhập email",
    sendReset: "Gửi",
    resetSent:
      "Đã gửi liên kết đặt lại tới email của bạn. Vui lòng kiểm tra hộp thư (cả mục Spam).",
    resetTitle: "Đặt mật khẩu mới",
    resetDesc: "Tạo mật khẩu mới để tiếp tục sử dụng tài khoản của bạn.",
    newPassword: "Mật khẩu mới",
    confirmNewPassword: "Xác nhận mật khẩu mới",
    updatePassword: "Cập nhật mật khẩu",
    errResetFill: "Vui lòng nhập và xác nhận mật khẩu mới.",
    errSamePassword: "Mật khẩu mới phải khác mật khẩu cũ.",
    errResetExpired:
      "Liên kết đặt lại đã hết hạn hoặc đã dùng. Hãy yêu cầu gửi lại.",
    resetSuccess: "Đổi mật khẩu thành công. Bạn có thể đăng nhập ngay.",
  },
  en: {
    tagline: "Smart money management for students",
    login: "Sign in",
    register: "Sign up",
    name: "Full name",
    username: "Username",
    email: "Email",
    phone: "Phone number",
    password: "Password",
    confirm: "Confirm password",
    forgot: "Forgot password?",
    submitLogin: "Sign in",
    submitRegister: "Create account",
    noAcc: "Don't have an account?",
    hasAcc: "Already have an account?",
    goRegister: "Sign up now",
    goLogin: "Sign in",
    streakLogin:
      "Sign in every day to maintain your login streak; it is recorded after a successful sign-in.",
    streakRegister:
      "After signing up, sign in consistently to maintain your login streak.",
    errFill: "Please fill in all the fields.",
    errLogin: "Please enter email and password.",
    errLen: "Password needs 8 characters, uppercase, lowercase, a number, and a special character.",
    pwStrength: "Password strength",
    pwWeak: "Weak",
    pwFair: "Fair",
    pwGood: "Good",
    pwStrong: "Strong",
    pwEight: "8 chars",
    pwUpper: "A–Z",
    pwLower: "a–z",
    pwNumber: "0–9",
    pwSpecial: "@#$",
    errMatch: "Password confirmation does not match.",
    errEmailOnly: "Please enter your email.",
    errInvalidCreds: "Incorrect email or password.",
    errEmailTaken: "This email is already registered.",
    errNotConfirmed: "Account not confirmed yet. Please check your email.",
    errTooMany: "Too many attempts, please try again in a few minutes.",
    errNetwork: "Cannot reach the server. Check your connection.",
    errLocked: "This account is locked. Please contact an administrator.",
    errProfile: "Could not load your profile. Please try again.",
    errPhone: "Phone number must be 9–15 digits (may start with +).",
    errUsernameTaken: "This username is already taken.",
    registered: "Signed up successfully! Please sign in.",
    loading: "Processing…",
    forgotTitle: "Recover password",
    forgotDesc: "Enter your registered email to reset your password.",
    emailLabel: "Email address",
    emailPlaceholder: "Enter email",
    sendReset: "Send",
    resetSent:
      "A reset link has been sent to your email. Please check your inbox (including Spam).",
    resetTitle: "Set a new password",
    resetDesc: "Create a new password to continue using your account.",
    newPassword: "New password",
    confirmNewPassword: "Confirm new password",
    updatePassword: "Update password",
    errResetFill: "Please enter and confirm your new password.",
    errSamePassword: "New password must differ from the old one.",
    errResetExpired:
      "This reset link has expired or was already used. Please request a new one.",
    resetSuccess: "Password updated successfully. You can now sign in.",
  },
};
