// Model: dữ liệu giao dịch mẫu (sau này lấy từ Supabase).
// mkey = phương thức thanh toán (dịch qua t.methods).
export const TXNS = [
  {
    id: 1,
    icon: "☕",
    cls: "c-coffee",
    name: "Trà sữa Phúc Long",
    date: "25/06",
    mkey: "ewallet",
    type: "out",
    amount: "-35.000 ₫",
  },
  {
    id: 2,
    icon: "🍜",
    cls: "c-food",
    name: "Cơm trưa căng tin",
    date: "25/06",
    mkey: "cash",
    type: "out",
    amount: "-45.000 ₫",
  },
  {
    id: 3,
    icon: "💰",
    cls: "c-salary",
    name: "Lương làm thêm",
    date: "24/06",
    mkey: "transfer",
    type: "in",
    amount: "+1.500.000 ₫",
  },
  {
    id: 4,
    icon: "🛵",
    cls: "c-move",
    name: "Đổ xăng",
    date: "24/06",
    mkey: "cash",
    type: "out",
    amount: "-65.000 ₫",
  },
  {
    id: 5,
    icon: "🎮",
    cls: "c-fun",
    name: "Vé xem phim CGV",
    date: "23/06",
    mkey: "card",
    type: "out",
    amount: "-120.000 ₫",
  },
  {
    id: 6,
    icon: "🎓",
    cls: "c-salary",
    name: "Học bổng kỳ 2",
    date: "22/06",
    mkey: "transfer",
    type: "in",
    amount: "+2.000.000 ₫",
  },
];
